########################################################################################################################
# Repo tool base settings
########################################################################################################################
[repo]
logging = "info"

# this lets repo_package know that we want to customize via package.toml
[repo_package.packages."omni-example-schema"]
omniverse_flow_version_scheme = true
package_per_config = true

# since our codeless schema doesn't generate any code, we don't need a package per config
[repo_package.packages."omni-example-codeless-schema"]
omniverse_flow_version_scheme = true
package_per_config = false